// <auto-generated />
using System;
using BankMore.ContaCorrente.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.ContaCorrente.Api.Migrations
{
    [DbContext(typeof(ContaCorrenteDbContext))]
    [Migration("20251109162220_EnhanceIdempotenciaEntity")]
    partial class EnhanceIdempotenciaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BankMore.ContaCorrente.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .HasColumnType("TEXT(37)")
                        .HasColumnName("idcontacorrente");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT(200)")
                        .HasColumnName("cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT(100)")
                        .HasColumnName("salt");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT(100)")
                        .HasColumnName("senha");

                    b.HasKey("IdContaCorrente");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("contacorrente", (string)null);
                });

            modelBuilder.Entity("BankMore.ContaCorrente.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<string>("ChaveIdempotencia")
                        .HasColumnType("TEXT(37)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT(2000)")
                        .HasColumnName("metadata");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasColumnType("TEXT(1000)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT(1000)")
                        .HasColumnName("resultado");

                    b.Property<string>("ResultadoHash")
                        .HasColumnType("TEXT(64)")
                        .HasColumnName("resultado_hash");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("idempotencia", (string)null);
                });

            modelBuilder.Entity("BankMore.ContaCorrente.Domain.Entities.Movimento", b =>
                {
                    b.Property<string>("IdMovimento")
                        .HasColumnType("TEXT(37)")
                        .HasColumnName("idmovimento");

                    b.Property<string>("DataMovimento")
                        .IsRequired()
                        .HasColumnType("TEXT(25)")
                        .HasColumnName("datamovimento");

                    b.Property<string>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("TEXT(37)")
                        .HasColumnName("idcontacorrente");

                    b.Property<char>("TipoMovimento")
                        .HasColumnType("TEXT(1)")
                        .HasColumnName("tipomovimento");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("valor");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("movimento", (string)null);
                });

            modelBuilder.Entity("BankMore.ContaCorrente.Domain.Entities.Movimento", b =>
                {
                    b.HasOne("BankMore.ContaCorrente.Domain.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Movimentos")
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("BankMore.ContaCorrente.Domain.Entities.ContaCorrente", b =>
                {
                    b.Navigation("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
